### ISSUE TITLE
Consider using "daily" queries for scouting in Event API 

### ISSUE THREAD

**Issue by aewhite** [CiscoSecurity/tr-05-serverless-gigamon-threatinsight#45]
In some cases, Secure X seems to only be interested in the last 100 events for an entity. However, Event API will attempt to search the entire requested time range for events (defaults to 7 days). In cases where the events for the target entity appear in all 7 then the backend system must merge/reduce/filter those results. However, if the entity doesn't have events for a given day, any requests targeting that day can return extremely quickly. 

The only benefit for querying an entire range is if you need to know the total event count for that query. Otherwise, querying each day sequentially should be considerably faster and less resource intensive on our end.

**Comment by ceilingduster** [comment]
Currently, Cisco SecureX threat response has a maximum of 200 entities in our graph.  Engineering is testing 500 nodes.  Its important to note that it may or may not be 200 entities unique.  You could have 2 vendors return (multiple results of) the same IP (which would be 2 nodes on the graph).

The 100 limit is more to ensure we do not exceed 30 seconds in timeout.

**Comment by aewhite** [comment]
If by limit, you mean the 100 event limit, then that does not materially improve the response time. The response time of the system is dominated by the number of events that are matched by the query *before* limits are applied.  A query that matches 0 documents can return in <10ms. A query that matches 100,000,000 events might take 10s. 

If you just want the last 100 events, then searching within the last 24h first will likely return those 100 events in sub second time. If the last 24h has no events (or not enough) then the result will return in <10ms. Repeat until you get the desired number of events.
